apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  strategy:
    type: Recreate    
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:15
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_PASSWORD
          value: "password"
        - name: POSTGRES_DB
          value: "userdb"
        - name: PGDATA
          value: "/var/lib/postgresql/data/pgdata"  
        volumeMounts:
        - name: postgres-persistant-storage
          mountPath: /var/lib/postgresql/data
          
      volumes:
      - name: postgres-persistant-storage
        persistentVolumeClaim:
          claimName: postgres-pvc


---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  type: ClusterIP
  ports:
  - port: 5432
    targetPort: 5432
  selector:
    app: postgres

