apiVersion: v1
kind: Service
metadata:
  name: mongo-express-service
spec:
  type: NodePort
  selector:
    app: mongo-express
  ports:
    - name : http
      port: 8081
      targetPort: 8081
      nodePort: 32222